apiVersion: apps/v1
kind: Deployment
metadata:
    name: mydeployment
spec:
   replicas: 1
   selector:
       app: deployment
   template: 
      metadata:
         name: testpod1
         labels:
            app: deployment
      spec:
        containers:
         - name: c00
           image: httpd
           ports:
            - containerPort: 80
            