apiVersion: v1
kind: ReplicationController
metadata: 
 name: mynginx-rc
spec: 
  replicas: 2
  selector: 
    app: mynginx
   template: 
   metadata: 
   labels: dev-env
     app: mynginx
    spec: 
      containers:
       - name: mynginx-container
         image: nginx
        ports: 
         - containerPort: 8080
         