apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/liveness
    livenessProbe:
      httpGet:
        path: /health/liveness
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      httpGet:
        path: /health/readiness
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3
    volumeMounts:
    - name: mongo-cred
      mountPath: /etc/cred
      readOnly: true
  volumes:
  - name: mongo-cred
    secret:
      secretName: mongo-cred
      items:
      - key: MONGO_ROOT_USERNAME
        path: admin/MONGO_ROOT_USERNAME
        mode: 0444
      - key: MONGO_ROOT_PASSWORD
        path: admin/MONGO_ROOT_PASSWORD
        mode: 0444